OAiES/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

#import views from main component
from main.views import landing_view, login_view, redir_view, userProf_view, dashboard_view, sucess_view, test_view, select_view

#import views from testBuilder component
from testBuilder.views import addMod, modSel, addTests, modulePage, addQuiz, qrPage, resultPg#, studentResult

from buildAssign.views import addAssign, atPage, addAnsw, aResultPg, addByFile

#import views from other components
#from registerAdmin.views import registerAdm
from register.views import registerUsr

urlpatterns = [
    #main page
    path('', landing_view, name='landing'),
    path('tinymce/', include('tinymce.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('landing/', landing_view, name="landingP"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html')),
    path('userProf/', userProf_view, name="userProf"),
    path('dashboard/', dashboard_view, name="Dash"),
    path('moduleAdd/', addMod, name="addModule"),
    path('addTests/', addTests, name="addTest"),
    path('addQuizQ/<str:pk>', addQuiz, name="addQuiz"),
    path('addAssignment/', addAssign, name="addAssign"),
    path('moduleSel/', modSel, name="selModule"),
    path('modulePage/<str:pk>/', modulePage, name="modulePage"),
    path('quizPage/<str:pk>/', qrPage, name="quizPage"),
    path('addAssignQ/<str:pk>/', addAnsw, name="addAssignQ"),
    path('addAssignFile/<str:pk>/', addByFile, name="addAssignFile"),
    path('assignPage/<str:pk>/', atPage, name="assignPage"),
    #path('resultPage/', qrPage, name="resultPage"),
    path('redir/', redir_view), #REMOVE LATER
    path('test/', test_view), #REMOVE LATER
    path('sucess/', sucess_view),
    path('select/', select_view),
    path('result/<str:pk>/', resultPg, name="resultPage"),
    path('aResult/<str:pk>/', aResultPg, name="aResultPage"),
    #path('resultStudent/<str:pk>/', studentResult, name="studentResPage"),
    #path('register/', registerAdm, name="Register"),
    #path('registerUser/', regisUsr_view, name="RegisterUser"),
    path('registerUser/', registerUsr, name="RegisterUser"),
    path('admin/', admin.site.urls),
]

buildAssign/models.py
from django.db import models
from testBuilder.models import Module
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django_quill.fields import QuillField
from tinymce import models as tinymce_models

class Assignment(models.Model):
    linked_module = models.ForeignKey(Module, on_delete=models.CASCADE, null=True)
    assign_name = models.CharField(max_length=1000, default="")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField()
    set_added = models.BooleanField(default=False)

    def __str__(self):
        return self.assign_name

class Answer(models.Model):
    link_assign = models.ForeignKey(Assignment, on_delete=models.CASCADE, null=True)
    host = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    #question = models.TextField(max_length=5000, default="")
    answer = models.CharField(max_length=5000, default="")
    question = tinymce_models.HTMLField()
    #answer = QuillField()
    created_date = models.DateTimeField()
    #set_added = models.BooleanField(default=False)

    def __str__(self):
        return self.question

class File(models.Model):
    link_answ = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    upload_txt = models.FileField(null=True, blank=True, validators=[FileExtensionValidator( ['txt'] ) ])
    uploader = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    link_assign = models.ForeignKey(Assignment, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.question + " " + self.uploader


class AssignResult(models.Model):
    link_ques = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True) 
    linked_assign = models.ForeignKey(Assignment, on_delete=models.CASCADE, null=True)
    attempted_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    correct = models.IntegerField(default=0)
    percentage = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    grade = models.CharField(max_length=10, default="")
    lettergrade = models.CharField(max_length=10, default="")
    attempted_time = models.DateTimeField()

    def __str__(self):
        return str(self.attempted_by)

register/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver

GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

ROLE_CHOICES = (
        ('A', 'Admin'),
        ('E', 'Educator'),
        ('S', 'Student'),
    )

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    school_faculty = models.TextField(max_length=150, blank=True, default="")
    programme = models.TextField(max_length=150, blank=True, default="")
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=False, default='M')
    role = models.CharField(max_length=1, choices=ROLE_CHOICES, blank=False, default='S')
    #birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.user)
"""
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
"""

testBuilder/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django_quill.fields import QuillField
from tinymce import models as tinymce_models

class Module(models.Model):
    module_name = models.CharField(max_length=120, default="")
    #module_desc = models.TextField(max_length=300, help_text="Resize textbox by dragging bottom right corner icon, if needed")
    module_desc = QuillField()
    host = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    #participants = models.ManyToManyField(User, related_name='participants', blank=True)

    def __str__(self):
        return self.module_name

# class UserToModule(models.Model):
#     module_linked = models.ForeignKey(Module, on_delete=models.CASCADE, null=True)
#     participants = models.ManyToManyField(User, related_name='participants', blank=True)

#     def __str__(self):
#         return self.module_linked


class Test(models.Model):
    test_name = models.CharField(max_length=100, default="")
    test_date = models.DateTimeField()
    module_sel = models.ForeignKey(Module, on_delete=models.CASCADE, null=True)
    host = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.test_name

class Quiz(models.Model):
    ANSWER_CHOICES = (
            ('option1', 'Answer Option 1'),
            ('option2', 'Answer Option 2'),
            ('option3', 'Answer Option 3'),
            ('option4', 'Answer Option 4'),
        )
    test_sel = models.ForeignKey(Test, on_delete=models.CASCADE, null=True)
    #quest = models.CharField(max_length=500, default="")
    quest = tinymce_models.HTMLField()
    op1 = tinymce_models.HTMLField()
    op2 = tinymce_models.HTMLField()
    op3 = tinymce_models.HTMLField()
    op4 = tinymce_models.HTMLField()
    # op1 = models.CharField(max_length=300, default="")
    # op2 = models.CharField(max_length=300, default="")
    # op3 = models.CharField(max_length=300, default="")
    # op4 = models.CharField(max_length=300, default="")
    answ = models.CharField(max_length=7, choices=ANSWER_CHOICES, blank=False, default='')
    #linked_assign = models.ForeignKey(Module, on_delete=models.CASCADE, null=True) #linking result to quiz questions model
    # answ = models.CharField(
    #     max_length=300, 
    #     help_text="Input option1 for the first option, option2 for the second option",
    #     default=""
    # )

    def __str__(self):
        return self.quest

class quizResult(models.Model):
    linked_test = models.ForeignKey(Test, on_delete=models.CASCADE) #linking result to test paper
    #linked_module = models.ForeignKey(Module, on_delete=models.CASCADE, null=True) #linking result to quiz questions model
    attempted_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    percentage = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    grade = models.CharField(max_length=10, default="")
    lettergrade = models.CharField(max_length=10, default="")
    #a_time = models.DateTimeField()
    attempted_time = models.DateTimeField()
    #userAnsw = models.CharField(max_length=10, default="")

    def __str__(self):
        return str(self.attempted_by)

"""
class quizAttempt(models.Model):
    linked_test = models.ForeignKey(Test, on_delete=models.SET_NULL, null=True)
    results_test = models.IntegerField()
    user_attempted = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    nums_test_attempted = models.IntegerField()
    nums_test_passed = models.IntegerField()
    #numbers_correct = models.IntegerField()
    #test_percentage = models.IntegerField()

    def __str__(self):
        return self.user_attempted
"""

"""
class dashboard(models.Model):
    class_students #get all students in user list
    class_pass_rates #calculate pass rate
    module_num_test #number of tests for the module
"""

templates/addAssignment.html
{% load static %}
{% include 'navbar.html' %}
{% comment %}
<link href="{% static 'css/formStyle.css'%}" rel="stylesheet">
<script src="{% static 'formStyle.js' %}"></script> {% endcomment %}
<link href="{% static 'css/inputwidth.css'%}" rel="stylesheet">

<div class="p-5 m-5">
  <div class="p-5 m-5">
    <div class="container form-style-7">
      <div class="col">
        <div class="m-5">
          <div class="m-5">
            <div class="m-5">
              <form class="form-style-7" method="post" autocomplete="off">
                {% csrf_token %}
                {{ mod_form.as_p }}
                <div class="mb-3"> <button class="btn btn-outline-primary w-100" type="submit">Add Assignment
                    Set</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/assignResult.html
{% load static %}
{% include 'navbar.html' %}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<link href="{% static 'css/testTable.css'%}" rel="stylesheet">
<script >
    function download_table_as_csv(table_id="id1", separator = ",") {
      // Select rows from table_id
      var rows = document.querySelectorAll("table#" + table_id + " tr");
      // Construct csv
      var csv = [];
        //looping through the table
      for (var i = 0; i < rows.length; i++) {
          var row = [], cols = rows[i].querySelectorAll("td, th");
             //looping through the tr
          for (var j = 0; j < cols.length; j++) {
             // removing space from the data
              var data = cols[j].innerText.replace(/(\r\n|\n|\r)/gm, "").replace(/(\s\s)/gm, " ")
               // removing double qoute from the data
              data = data.replace(/"/g, `""`);
              // Push escaped string
              row.push(`"` + data + `"`);
          }
          csv.push(row.join(separator));
      }
      var csv_string = csv.join("\n");
      // Download it
      var filename = "export_" + table_id + "_" + new Date().toLocaleDateString() + ".csv";
      var link = document.createElement("a");
      link.style.display = "none";
      link.setAttribute("target", "_blank");
      link.setAttribute("href", "data:text/csv;charset=utf-8," + encodeURIComponent(csv_string));
      link.setAttribute("download", filename);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
  }
</script>

<div class="main-content">
    <div class="container mt-7">
        <div class="row">
            <div class="col">
              <div class="card shadow">
                <div class="card-header border-0">
                  <div>
                      <h2 class="mb-0">
                          Results
                      </h2>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush" id="id1">
                    <thead class="thead-light">
                      <tr>
                        <th scope="col">
                            Percentage
                        </th>
                        <th scope="col">
                            Grade
                        </th>
                        <th scope="col">
                            No. of correct keyword(s)
                        </th>
                        <th scope="col">
                           Total Keyword(s)
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>
                                {{percent}}%
                            </th>
                            <th>
                                {{grade}}
                            </th>
                            <th>
                                {{correct}}
                            </th>
                            <th>
                                {{total}}
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div>
            <br/>
            <a href="{% url 'selModule' %}" class="btn btn-outline-primary w-100">
              <i class="fas fa-link"></i>
              Click Here to Return To Module Page
            </a>
            <button class="btn btn-outline-primary w-100" onclick="download_table_as_csv();">Download CSV</button>
          </div>
    </div>
</div>  

templates/formStyle.html
{% load static %}
{% include 'navbar.html' %}
<link href="{% static 'css/formStyle.css'%}" rel="stylesheet">
<script src="{% static 'formStyle.js' %}"></script> 

<form class="form-style-7">
    <ul>
        <li>
            <label for="name">Name</label>
            <input type="text" name="name" maxlength="100">
            <span>Enter your full name here</span>
        </li>
        <li>
            <label for="email">Email</label>
            <input type="email" name="email" maxlength="100">
            <span>Enter a valid email address</span>
        </li>
        <li>
            <label for="url">Website</label>
            <input type="url" name="url" maxlength="100">
            <span>Your website address (eg: http://www.google.com)</span>
        </li>
        <li>
            <label for="bio">About You</label>
            <textarea name="bio" onkeyup="adjust_textarea(this)"></textarea>
            <span>Say something about yourself</span>
        </li>
        <li>
            <input type="submit" value="Send This" >
        </li>
    </ul>
</form>
<section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>Online Assessment Tool</h1>
          <h2>A learning management system with an assessment tool</h2>
        </div>
      </div>
      <div class="text-center">
        <a href="#about" class="btn-get-started scrollto">Get Started</a>
      </div>

        <div class="row icon-boxes">
            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon-box">
                <div class="icon"><i class="ri-stack-line"></i></div>
                <h4 class="title"><a href="">Lorem Ipsum</a></h4>
                <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
                <div class="icon-box">
                <div class="icon"><i class="ri-palette-line"></i></div>
                <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
                <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
                <div class="icon-box">
                <div class="icon"><i class="ri-command-line"></i></div>
                <h4 class="title"><a href="">Magni Dolores</a></h4>
                <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
                <div class="icon-box">
                <div class="icon"><i class="ri-fingerprint-line"></i></div>
                <h4 class="title"><a href="">Nemo Enim</a></h4>
                <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
            </div>
        </div>
      </div>
    </div>
  </section>

templates/generateResult.html
{% load static %}
{% include 'navbar.html' %}
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<link href="{% static 'css/testTable.css'%}" rel="stylesheet">
<script >
    function download_table_as_csv(table_id="id1", separator = ",") {
      // Select rows from table_id
      var rows = document.querySelectorAll("table#" + table_id + " tr");
      // Construct csv
      var csv = [];
        //looping through the table
      for (var i = 0; i < rows.length; i++) {
          var row = [], cols = rows[i].querySelectorAll("td, th");
             //looping through the tr
          for (var j = 0; j < cols.length; j++) {
             // removing space from the data
              var data = cols[j].innerText.replace(/(\r\n|\n|\r)/gm, "").replace(/(\s\s)/gm, " ")
               // removing double qoute from the data
              data = data.replace(/"/g, `""`);
              // Push escaped string
              row.push(`"` + data + `"`);
          }
          csv.push(row.join(separator));
      }
      var csv_string = csv.join("\n");
      // Download it
      var filename = "export_" + table_id + "_" + new Date().toLocaleDateString() + ".csv";
      var link = document.createElement("a");
      link.style.display = "none";
      link.setAttribute("target", "_blank");
      link.setAttribute("href", "data:text/csv;charset=utf-8," + encodeURIComponent(csv_string));
      link.setAttribute("download", filename);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
  }
</script>

<div class="main-content">
    <div class="container mt-7">
        <div class="row">
            <div class="col">
              <div class="card shadow">
                <div class="card-header border-0">
                  <div>
                      <h2 class="mb-0">
                          Results
                      </h2>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush" id="id1">
                    <thead class="thead-light">
                      <tr>
                        <th scope="col">
                            Percentage
                        </th>
                        <th scope="col">
                            Grade
                        </th>
                        <th scope="col">
                            No. of correct answers
                        </th>
                        <th scope="col">
                            No. of wrong answers
                        </th>
                        <th scope="col">
                           Total Questions
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>
                                {{percent}}%
                            </th>
                            <th>
                                {{grade}}
                            </th>
                            <th>
                                {{correct}}
                            </th>
                            <th>
                                {{wrong}}
                            </th>
                            <th>
                                {{total}}
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div>
            <br/>
            <a href="{% url 'selModule' %}" class="btn btn-outline-primary w-100">
              <i class="fas fa-link"></i>
              Click Here to Return To Module Page
            </a>
            <button class="btn btn-outline-primary w-100" onclick="download_table_as_csv();">Download CSV</button>
          </div>
    </div>
</div>  

templates/landingpage.html
{% load static %}
<link href="{% static 'css/login.css'%}" rel="stylesheet">
<link href="{% static 'css/custStyle1.css'%}" rel="stylesheet">

{% include 'navbar.html' %}

<section class="sectionCust">
  <div class="container">
    {% comment %} <div class="container mt-5 pt-5"> {% endcomment %}
    <div class="row d-flex justify-content-center">
        <!-- left side; image  -->
        <div class="col-md-6">
            <img src="{% static 'images/aboutUs.png' %}" width="700" height="450"/>                
        </div>
        <!-- right side; card -->
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <div>
                  <h1 class="colH1"><b>What is OAiES?</b></h1>
                  <br/>
                  <h2 class="custH2">OAiES is a system that allows educators to create tests for students to complete/answer.</h2>
                  <br/>
                  <h2 class="custH2">OAiES allows educators to view students' results for any specific test set.</h2>
                  <br/>
                  <h2 class="custH2">OAiES also allows students to view their own test results.</h2
                </div>
            </div>
        </div>
    </div>
  </div>
  {% comment %} <h1 class="text-center colH1"><b>Main Features of OAiES</b></h1>
 <div class="container mt-2">
    <div class="row d-flex justify-content-center">
        <!-- left side; image  -->
        <div class="col-md-6">
            <img src="{% static 'images/Form.png' %}" width="700" height="450"/>                
        </div>
        <!-- right side; card -->
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <div>
                  <h1 class="custH1">Create Tests</h1>
                  <br/>
                  <h2 class="custH2">description</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<hr class="new3">
<div class="container"> 
  <div class="row d-flex justify-content-center">
      <!-- left side; image  -->
      <div class="col-md-6">
        <div class="card px-5 py-5" id="form1">
          <div>
            <h1 class="custH1">Complete Tests</h1>
            <br/>
            <h2 class="custH2">description</h2>
          </div>
        </div>
      </div>
      <!-- right side; card -->
      <div class="col-md-6">
        <img src="{% static 'images/examImg.png' %}" width="700" height="450"/>                
      </div>
  </div>
</div>
<hr class="new3">
<div class="container">
  <div class="row d-flex justify-content-center">
      <!-- left side; image  -->
      <div class="col-md-6">
          <img src="{% static 'images/dashboardImg.png' %}" width="700" height="450"/>                
      </div>
      <!-- right side; card -->
      <div class="col-md-6">
          <div class="card px-5 py-5" id="form1">
              <div>
                <h1 class="custH1">View Results</h1>
                <br/>
                <h2 class="custH2">OAiES allows students to view their own results, and also allows educators to view every results for a test set.</h2>
              </div>
          </div>
      </div>
  </div>
</div> {% endcomment %}
{% comment %} <div class="container">
  <div class="row d-flex justify-content-center">
    <!-- left side; image  -->
    <div class="col-md-6">
      <div class="card px-5 py-5" id="form1">
        <div>
          <h1 class="custH1">Title</h1>
          <h2 class="custH2">description</h2>
        </div>
      </div>
    </div>
    <!-- right side; card -->
    <div class="col-md-6">
      <img src="{% static 'images/analysisImg.png' %}" width="700" height="450"/>                
    </div>
  </div>
</div>  {% endcomment %}
</section>

templates/resultPage.html
{% load static %}
{% include 'navbar.html' %}

<div class="p-5 m-5">
    <div class="card">
        <form method='post' action=''>
            {% csrf_token %}
            <p>
                <label for="id_correct">Correct:</label> 
                <input type="number" name="correct" required id="id_correct" value="{{correct}}" readonly>
            </p>
            <p>
                <label for="id_wrong">Wrong:</label> 
                <input type="number" name="wrong" required id="id_wrong" value="{{wrong}}" readonly></p>
            <p><label for="id_percentage">Percentage:</label> <input type="number" name="percentage" required id="id_percentage" value="{{percent}}" readonly>
            </p>
            <p>
                <label for="id_total">Total:</label> 
                <input type="number" name="total" required id="id_total" value="{{total}}" readonly>
            </p>
            <p>
                <label for="id_grade">Grade:</label> <input type="text" name="grade" maxlength="10" required id="id_grade" value="{{grade}}" readonly>
            </p>
            <div class="mb-3"> <button class="btn btn-outline-primary w-100" type="submit">Submit Results</button> </div> 
        </form>
    </div>
</div>

{% comment %} {{ form.as_p }} {% endcomment %}
{% comment %}
<p><label for="id_correct">Correct Answer(s):</label> <input type="text" name="correct" maxlength="10" required id="id_correct" readonly value="{{correct}}"></p>
<p><label for="id_wrong">Wrong Answer(s):</label> <input type="text" name="wrong" maxlength="10" required id="id_wrong" readonly value="{{wrong}}"></p>
<p><label for="id_percentage">Percentage:</label> <input type="text" name="percentage" maxlength="10" required id="id_percentage" readonly value="{{percent}}%"></p>
<p><label for="id_total">Total:</label> <input type="text" name="total" maxlength="10" required id="id_total" readonly value="{{total}}"></p>
<p><label for="id_grade">Grade:</label> <input type="text" name="grade" maxlength="10" required id="id_grade" readonly value="{{grade}}"></p>
{% endcomment %}

templates/sucessPage.html
{% load static %}
{% include 'navbar.html' %}

<div class="p-5 m-5">
    <div class="p-5 m-5">
        <div class="row d-flex justify-content-center">
            <div class="col-4">
            </div>
            <div class="col-4">
                <img src="{% static 'images/sucess.png' %}" width="450" height="450"/>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>
</div>

templates/testSelect.html
{% load static %}
{% include 'navbar.html' %}
<link href="{% static 'css/testTable.css'%}" rel="stylesheet">

templates/userProfile.html
{% load static %}
{% include 'navbar.html' %}
<link href="{% static 'css/login.css'%}" rel="stylesheet">

<div class="container mt-5 pt-5">
    <div class="row d-flex justify-content-center">
        <!-- left side; image  -->
        <div class="col-md-6">
            <img src="{% static 'images/profileImg.png' %}" width="700" height="450"/>                
        </div>
        <!-- right side; card -->
        <div class="col-md-6">
            <div class="card " id="form1">
                <div class="form-data">
                    {% for p in prof %}
                    <p></p>
                    <br/>
                    <h3>User Profile</h3>
                    <br/>
                    <div class="forms-inputs mb-4"> <label>Name</label> 
                        <input class="w-100" autocomplete="off" type="text" value="{{user.first_name}}&nbsp;{{user.last_name}}" readonly>
                    </div>
                    <div class="forms-inputs mb-4"> <label>Email</label> 
                        <input class="w-100" autocomplete="off" type="text" value="{{user.email}}" readonly>
                    </div>
                    <div class="forms-inputs mb-4"> <label>Gender</label> 
                        <input class="w-100" autocomplete="off" type="text" value={{p.get_gender_display}} readonly>
                    </div>
                    <div class="forms-inputs mb-4"> <label>School/Faculty</label> 
                        <input class="w-100" autocomplete="off" type="text" value={{p.school_faculty}} readonly>
                    </div>
                    <div class="forms-inputs mb-4"> <label>Programme Name</label>
                        <input class="w-100" autocomplete="off" type="text" value={{p.programme}} readonly>
                    </div>
                    <div class="forms-inputs mb-4"> <label>Role</label>
                        <input class="w-100" autocomplete="off" type="text" value={{p.get_role_display}} readonly>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>